Setup: Everything Works

diff --git a/Project1/Setup b/Project1/Setup
--- a/Project1/Setup
+++ b/Project1/Setup
@@ -2,6 +2,8 @@
 
 # Setup Script
 
+# Step 1: CHecking if the script is being run as root 
+
 # Before starting check if the script is run as root (EUID 0) or with sudo privileges
 # $EUID is 0 when running as root, so this will check if you have the correcet permissions
 #
@@ -11,37 +13,42 @@ if [ "$EUID" -ne 0 ]; then
 fi
 
 # -------------------------------------------------------------------------------------
-# Step 1: Command line Options
+# Step 2: Command line Options
 
 # This part will handle the user's input from the command line.
-# Will use 'getopts' to parse the command line options.
-
+# Will use 'getopts' to handle the options (like -p or -c) the user gives when running the script
+#
 while getopts "pc" opt; do
     case "$opt" in
         # The -p option will install the packages
         p)
             # Check if the Packages script exists
             if [ -f "./Packages" ]; then
-                bash ./Packages  || { echo "Error running Packages Script"; exit 1; }
+                bash ./Packages || { echo "Error running Packages Script"; exit 1; }
+		# it runs the script , but if the running script fails
             else
+		    # if it dont exist
                 echo "Cannot find the Package script"
                 exit 1
             fi
             ;;
+
+
 
         # The -c option will install the Configuration
         c)
             # Check if the Configuration script exists
             if [ -f "./Configuration" ]; then
                 bash ./Configuration || { echo "Error running Configuration script"; exit 1; }
+		# this runs the script, if the script fails to run 
             else
                 echo "Cannot find the Configuration script"
                 exit 1
             fi
             ;;
 
-        # This will handle the invalid options
-        *)
+        *) # if the user enters a invalid option
+
             echo "Invalid options: -$opt"
             echo "Usage: -p for installing packages, -c for setting up configurations"
             exit 1
@@ -49,6 +56,12 @@ while getopts "pc" opt; do
     esac
 done
 
+# -----------------------------------------------------------------------------------
+
+# Step 3: Check if no options were provided
+# $OPTIND will tells which option was processed last
+
+# if its 1 then it means no option was provided 
 # If the user didn't provide anything:
 if [ $OPTIND -eq 1 ]; then
     echo "Please provide either option -c, -p or both"
